In [207]:
# Import semua library yang dibutuhkan
import pandas as pd
import numpy as np
import scipy.stats as scp

In [208]:
# mencari jumlah nilai unik pada kolom yang bertipe kategorik
def check_uniqueness(df):
    for col in df.select_dtypes(include=object).columns:
        print('No. of unique values in column '+col+':')
        print(df[col].value_counts(),'\n')
        
# mengecek nilai null
def check_null(df):
    col_na = df.isnull().sum().sort_values(ascending=True)
    percent = col_na / len(df) * 100
    missing_data = pd.concat([col_na, percent], axis=1, keys=['Total', 'Percent'])

    if (missing_data[missing_data['Total'] > 0].shape[0] == 0):
        print("Tidak ditemukan missing value pada dataset")
    else:
        print(missing_data[missing_data['Total'] > 0])

# mengecek nilai duplikat
def check_duplicates(df):
    dup = df.duplicated()
    print("Jumlah duplikasi data : " + str(dup.sum()))

In [209]:
df = pd.read_csv('matches.csv')

In [210]:
check_duplicates(df)

Jumlah duplikasi data : 0

In [211]:
check_null(df)

       Total   Percent
Patch    411  6.420872

In [212]:
patch = df['Patch']

In [213]:
from datetime import datetime

start_patch0 = datetime(2020, 4, 15)
end_patch0 = datetime(2020, 6, 2)

start_patch1 = datetime(2020, 6, 2)
end_patch1 = datetime(2021, 1, 12)

start_patch2 = datetime(2021, 1, 12)
end_patch2 = datetime(2021, 6, 22)

start_patch3 = datetime(2021, 6, 22)
end_patch3 = datetime(2022, 1, 11)

def handle_patch_null(row):
    if pd.isnull(row['Patch']):
        date = row['Date'][:10]
        date_object = datetime.strptime(date, '%Y-%m-%d')
        if start_patch0 <= date_object < end_patch0:
            row['Patch'] = 'Patch 0.0'
        if start_patch1 <= date_object < end_patch1:
            row['Patch'] = 'Patch 1.0'
        if start_patch2 <= date_object < end_patch2:
            row['Patch'] = 'Patch 2.0'
        if start_patch3 <= date_object < end_patch3:
            row['Patch'] = 'Patch 3.0'
    else:
        return row

In [214]:
df = df.apply(handle_patch_null, axis=1)

In [215]:
df

,No,MatchID,Date,Patch,EventID,EventName,EventStage,Team1ID,Team2ID,Team1,Team2,Team1_MapScore,Team2_MapScore
0,0.0,62393.0,2022-01-08 15:30:00,Patch 3.12,826.0,Nerd Street Gamers Winter Championship - Regio...,Group Stage: Decider (A),6903.0,6020.0,Booster Seat Gaming,Pho Real,2.0,1.0
1,1.0,62403.0,2022-01-08 15:30:00,Patch 3.12,826.0,Nerd Street Gamers Winter Championship - Regio...,Group Stage: Decider (C),7046.0,7047.0,Bjor's Kittens,Mugiwara,2.0,0.0
2,2.0,62391.0,2022-01-08 12:30:00,Patch 3.12,826.0,Nerd Street Gamers Winter Championship - Regio...,Group Stage: Winner's (A),6461.0,6903.0,Akrew,Booster Seat Gaming,2.0,1.0
3,3.0,62396.0,2022-01-08 12:30:00,Patch 3.12,826.0,Nerd Street Gamers Winter Championship - Regio...,Group Stage: Winner's (B),6164.0,7043.0,Radiance,sameROFLMAO,2.0,0.0
4,5.0,62402.0,2022-01-08 12:30:00,Patch 3.12,826.0,Nerd Street Gamers Winter Championship - Regio...,Group Stage: Elimination (C),7047.0,3545.0,Mugiwara,CLG Red,2.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6396,NaN,NaN,None,None,NaN,None,None,NaN,NaN,None,None,NaN,NaN
6397,NaN,NaN,None,None,NaN,None,None,NaN,NaN,None,None,NaN,NaN
6398,NaN,NaN,None,None,NaN,None,None,NaN,NaN,None,None,NaN,NaN
6399,NaN,NaN,None,None,NaN,None,None,NaN,NaN,None,None,NaN,NaN
6400,NaN,NaN,None,None,NaN,None,None,NaN,NaN,None,None,NaN,NaN

In [216]:
check_null(df)

                Total   Percent
No                411  6.420872
MatchID           411  6.420872
Date              411  6.420872
Patch             411  6.420872
EventID           411  6.420872
EventName         411  6.420872
EventStage        411  6.420872
Team1ID           411  6.420872
Team2ID           411  6.420872
Team1             411  6.420872
Team2             411  6.420872
Team1_MapScore    411  6.420872
Team2_MapScore    411  6.420872

In [217]:
# df['Patch_Version'] = df['Patch'].str.extract(r'(\d)\.\d+').astype(float)
# df['Patch_Version'].value_counts()